services:
  - type: web
    name: occulta-scraper
    env: python
    plan: free
    rootDir: scraper
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: REDDIT_CLIENT_ID
      - key: REDDIT_CLIENT_SECRET
      - key: REDDIT_USER_AGENT
      - key: OPENAI_API_KEY
      - key: SUPABASE_URL
      - key: SUPABASE_KEY
