// app/api/send-daily-drop/route.ts

import { NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function GET() {
  const { data: subscribers, error: subError } = await supabase
    .from('subscribers')
    .select('email')

  if (subError || !subscribers || subscribers.length === 0) {
    return NextResponse.json({ error: 'No subscribers found' }, { status: 400 })
  }

  const { data: insights, error: insightError } = await supabase
    .from('insights')
    .select('id, signal, why_it_matters')
    .order('urgency_score', { ascending: false })
    .order('novelty_score', { ascending: false })
    .limit(10)

  if (insightError || !insights) {
    return NextResponse.json({ error: 'Failed to fetch insights' }, { status: 500 })
  }

  const top4 = insights.slice(0, 4)

  const html = `
    <div style="font-family: DM Mono, monospace; background-color: #0f0f0f; padding: 24px; color: #e5e5e5; max-width: 640px; margin: auto; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 32px;">
        <img src="https://occulta.ai/occulta-logo.png" alt="Occulta Logo" width="140" style="margin: 0 auto; display: block;" />
        <h1 style="color: #a855f7; margin-top: 16px; font-size: 24px;">Daily Drop</h1>
        <p style="color: #999; font-size: 14px;">The four most intriguing signals of the last 24h</p>
      </div>
      ${top4.map(signal => `
        <div style="margin-bottom: 36px; padding: 20px; background: #1a1a1a; border-radius: 10px; box-shadow: 0 0 12px #a855f770; border: 1px solid #a855f7;">
          <h2 style="color: #ffffff; font-size: 18px; margin-bottom: 8px;">🔍 ${signal.signal}</h2>
          <p style="color: #bbbbbb; font-size: 14px; margin-bottom: 12px;">${signal.why_it_matters}</p>
          <a href="https://occulta.ai/signal?id=${signal.id}" style="color: #a855f7; font-weight: bold; text-decoration: none;">View Full Signal ↗</a>
        </div>
      `).join('')}
      <div style="border-top: 1px solid #333; padding-top: 24px; text-align: center; font-size: 12px;">
        <p style="color: #999999;">You’re receiving this because you subscribed to Occulta’s radar.</p>
        <p style="color: #999999;"><a href="https://occulta.ai/unsubscribe" style="color: #a855f7; text-decoration: none;">Unsubscribe</a> if you'd like to disable future drops.</p>
        <p style="margin-top: 12px; color: #444;">This transmission was generated by Occulta AI at ${new Date().toUTCString()}</p>
      </div>
    </div>
  `

  for (const { email } of subscribers) {
    console.log('Sending to:', email)
    await resend.emails.send({
      from: 'Occulta <onboarding@resend.dev>',
      to: email,
      subject: '🧠 Occulta Daily Trend Drop',
      html
    })
  }

  return NextResponse.json({ success: true })
}
